---
# tasks file for vector-role
- name: Download Vector
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "/tmp/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    mode: 0755
    timeout: 60
    force: true
    validate_certs: false
  register: get_vector
  until: get_vector is succeeded
- name: Create vector home dir
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ vector_home }}"
- name: Extract vector to home dir
  become: true
  ansible.builtin.unarchive:
    copy: false
    src: "/tmp/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "{{ vector_home }}"
    extra_opts: [--strip-components=2]
    creates: "{{ vector_home }}/bin/vector"
- name: Set environment Vector
  become: true
  ansible.builtin.template:
    src: templates/vector.sh.j2
    dest: /etc/profile.d/vector.sh